### ISSUE TITLE
Collecting Multiple MFT's/USNJournals

### ISSUE THREAD

**Issue by devin-hill** [OMENScan/AChoir#4]
Many systems we work with have multiple physical disks and we'd like to pull the MFT's for each. I've been able to work out some code that partially works. It will collect the MFT's from both disks on my test system, but it overwrites the first one with the second, as they both use the same name. My code is below. In the NCP line I've tried modifying the &Acq portion with different filenames: for example "&Acq\\&Lst.mft", but it just doesn't write anything when I do that. At this point I'm probably just going to call a batch file to do this externally, but this would be a great feature to have natively in Achoir. Same goes for the USN Journals for each disk, as well.

CMD:mkdir Drives
CMD:wmic logicaldisk WHERE drivetype=3 get caption | findstr /v "Caption" > Drives\drives.txt
ACQ:\RawData
LST:Drives\drives.txt
NCP:"&Lst:\$MFT" "&Acq"

**Comment by OMENScan** [comment]
Sorry you had problems with it.

There are a couple of things going on here...

First - That WMIC command redirect output to file is going to write out some additional spaces (0x20) and a blank line . So we need to get rid of (parse out) those to construct the NCP: line(s) properly.

Second - There is a Limitation/Bug in the current version of AChoir such that the &LST variable has to be at the very end of the line. Everything after it is ignored. I've fixed it in the next release which will be available soon. But for now, we need to work around it by constructing LST: / &LST a little differently.

I admit it's a bit of a kludge - but you can get around these limitations by doing something like:

ACQ:\Drives
CMD:DEL "&DIR\Drives.txt"
CMD:DEL "&DIR\DVParse.txt"
CMD:wmic logicaldisk WHERE drivetype=3 get drivetype, deviceid | findstr "3" > &DIR\Drives.txt
CMD:for /F "tokens=1" %%A in (&DIR\Drives.txt) do echo %%A\$MFT &ACQ>>"&DIR\DVParse.txt"
LST:DVParse.txt
NCP:&LST


Also - be aware - I anticipated that &LST would be a static file - and part of the toolkit ( not created dynamically in this way) - So doing it this way breaks some of the non-repudiation I built into AChoir by  creating separate output directors for each acquisition - (this method is writing to the AChoir Toolkit directory) - but It can be done this way - and I wanted to allow Examiners the freedom to use it any way they wanted...  Just something to think about.

Edit - Please note - the github editor changes some of the text in this post - So the text in the 5th line of the AChoir Script should be percent-percent-A-BackSlash-Dollar-MFT (Not percent-percent-A-Dollar-MFT).

**Comment by devin-hill** [comment]
Great, thanks for the quick response! I'll give this a try. I did run into problems with that text file as you mentioned, so I was just testing with a static file until I could figure out if collecting all MFT's was possible with Achoir or not. The issue with LST having to be at the end explains some of the trouble I was having, as well. Everything after it seemed to be getting cut off but I couldn't figure out if it was something in Achoir or if I just didn't understand how it worked.

I may try to work the Drives folder back into the acquisition directory, but when I was doing that before it kept parsing an additional "C:\Achior" into the path, so I would end up with "C:\AchoirC:\Achoir\Acquisitiondir\Drives\drives.txt" instead of just "C:\Achoir\Acquisitiondir\Drives\drives.txt" when trying to call it. 

Thanks again for the help. We may be replacing our current PowerShell live response kit with Achoir, so I'll be sure to bring up any other bugs/quirks we run into in the process.

**Comment by OMENScan** [comment]
I've added a new DSK: action and &DSK variable to the v1.0 Release Candidate.  I am testing it now, and will be releasing in the next couple days.  With this new Action you can tell AChoir to find Types of Attached Disks (Remote, Fixed, CDROM, Ramdisk, etc...) which sets the &DSK variable array.  This should give you the functionality you need. (i.e. DSK:Fixed)

**Comment by OMENScan** [comment]
AChoir v1.0 has been released!

This functionality (DSK: / &DSK) is now implemented in a number of the included scripts - You can check them out to see how it works.
